### ISSUE TITLE
Dispatching a punctuation change stops speech

### ISSUE THREAD

**Issue by parhamdoustdar** [robertmeta/swiftmac#19]
Not sure if I'm debugging this correctly, but here is what I've got for what it's worth.

First, to reproduce the issue:

1. Switch to the Swiftmac server and press `C-e x b` to read battery status. Note that you hear nothing
2. Switch to the Mac speech server and do the same, and you should hear the status

I had a look at the logs, and this seems to be what Swiftmac is receiving from Emacspeak:

```
tts_set_punctuations some
d
s
tts_sync_state some 1 0 250
c {[{voice systemDefault}] }
q {Power AC,  }
c {[{voice systemDefault}] }
q {battery charging (47% load,  }
c {[{voice systemDefault}] }
q {remaining time 1:04) }
d
tts_set_punctuations all
d
```

If you paste this into Swiftmac in terminal, you should get nothing spoken. Make sure to add a newline at the end so that the last line, `d` is also sent in terminal.

This makes me think that dispatching the command to set a different punctuation stops speech, even though there is no `s` command sent.

**Comment by robertmeta** [comment]
Ugh, I think I mis-implemented the tts_* commands, I didn't understand they were to be queued like everything else... I think I saw tts_say and thought that since they were setting stuff up it wasn't to be queued ... but with intermixing punctuation it would need to be.  

This is going to require a little bit of thought to fix properly... that will be a v2 concern I think I can kludge this for v1 with a check for empty speaker content in dispatch.

**Comment by robertmeta** [comment]
@parhamdoustdar So, fixed in v1 --- you should be able to pull for the fix, and I am going to relabel this issue for v2, because I should properly have stuff wither queued or not queued.

**Comment by robertmeta** [comment]
OK... not fixed, but improved, it no longer gives nothing but since the punct change races out ahead of the rest, it ends up back in all puncs... ugh.

**Comment by parhamdoustdar** [comment]
Ooh, this sounds complicated. Are the other speech servers asynchronous as well? I can see what you are talking about re the race condition. I know that the python server just used a queue, but I wonder if other servers have a better solution.

**Comment by robertmeta** [comment]
The queue is perfectly workable, and I use a worse model right now, part of this is I wrote swiftmac while learning emacspeak.

I now know much better way to do it, need to confirm some things with the list, but I think I know how it should be done.

**Comment by robertmeta** [comment]
This is fixed and is now a more general problem for the next version.
