### ISSUE TITLE
Convert pbas/pmod to just straight tts_set_pitch_multiplier

### ISSUE THREAD

**Issue by robertmeta** [robertmeta/swiftmac#23]
I think you are already working on this, flows into the new swiftmac-voices.el.

**Comment by parhamdoustdar** [comment]
I had a look at the code, and here is what I found:
1. `pbas` could be ported to mac voices as "pitch", as the value seems to be an integer between 0-100
2. `pmod` is not defined in mac voices, as it is about how "animated" the voice is, as in, how much the pitch varies during speech
My suggestion would be to use `pbas` as a pitch setting and ignore `pmod` for now. What do you think?
if yes, would the value of 1-100 be directly portable to how the MacOS pitch can be specified?

**Comment by robertmeta** [comment]
With pbas, what is "neutral"? Assuming it is 50, yeah, it would be a bit of easy
math, with diverging scales 1-50 maps to .5 to 1.0 and 50 to 100 from 1.0 to 2.0. 

There is an elegant solution to map it I am sure, but at the end of the day 
it is basically if below 50, scale 1 to 50 to .51 to 1, and on the other side
from 51 to 100, scale from 1.02 to 2.0.

> On Apr 17, 2024, at 06:18, Parham Doustdar ***@***.***> wrote:
> 
> 
> I had a look at the code, and here is what I found:
>     • pbas could be ported to mac voices as "pitch", as the value seems to be an integer between 0-100
>     • pmod is not defined in mac voices, as it is about how "animated" the voice is, as in, how much the pitch varies during speech
> My suggestion would be to use pbas as a pitch setting and ignore pmod for now. What do you think?
> if yes, would the value of 1-100 be directly portable to how the MacOS pitch can be specified?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

--
Robert Melton
***@***.***

**Comment by bartbunting** [comment]
As I recall some of these parameters were done using effects with socs
It was an attempt to add other dimensions to the voices. For example, using echo and different filters. I'm not sure if there's any possibility to do something similar with the new server?

**Comment by bartbunting** [comment]
We don't need to do math on the bus value. We can simply redefine it in swiftmac-voices.el

**Comment by robertmeta** [comment]
This is now in the system as [[pitch ...]]

**Comment by robertmeta** [comment]
@bartbunting closing this as you mentioned it is straightforward, I am considering it part of #28
