### ISSUE TITLE
Create swiftmac-setup.el instead of swiftmac-voices.el 

### ISSUE THREAD

**Issue by robertmeta** [robertmeta/swiftmac#25]
This is a large ticket to create a swiftmac-setup.el that would do stuff like

- setup defcustoms for the settings swiftmac supports
- use dynamic voice selection (need separate ticket for this)
- add to key places in the code like the multi servers, example: 
  (push "swiftmac" tts-multi-engines)
- make it use new features like tts_set_pitch_multiplier and if possible tts_set_voice instead of the embedded voice codes, in a perfect world, no more embeddings / codes 
- (maybe) allow different voices for like comments versus code, I think I would like this 
- (maybe) new features like rate change on numbers.

**Comment by robertmeta** [comment]
(defvar dtk-handle-unicode nil)

We need to set this to true in our setup cause we can handle unicode.

**Comment by parhamdoustdar** [comment]
This seems to be in conflict with #28. Given that doing #28 means Emacspeak automatically applies these settings when anyone uses Emacspeak on MacOS, I'm more in favor of #28. Maybe we can move these pieces to that issue?

**Comment by robertmeta** [comment]
Yep, closing and moving
