### ISSUE TITLE
No way to select one of the two voices with the same name

### ISSUE THREAD

**Issue by parhamdoustdar** [robertmeta/swiftmac#29]
This will be hard to reproduce if someone doesn't have the [Espeak-NG for MacOS](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://apps.apple.com/us/app/espeak-ng/id6444089174&ved=2ahUKEwi1rqz8kseFAxW5hP0HHRnfCZ0QFnoECBMQAQ&usg=AOvVaw2J8tE2Pc_NUL03P4rN0W78) installed, but if you do, you get two voices called Alex – one from that app and one that comes with MacOS.
When I pass `:Alex` to Swiftmac, I get the Alex from eSpeak.

**Comment by robertmeta** [comment]
@parhamdoustdar fair point, I could make you able to pass in the full idenitifier but where would you even get that? That is like com.apple.blah.blah.Alex

**Comment by parhamdoustdar** [comment]
This may be a legitimate use case for implementing a way of Emacspeak getting a list of voices from the server?Sent from my iPhoneOn 16 Apr 2024, at 21:13, Robert Melton ***@***.***> wrote:﻿
@parhamdoustdar fair point, I could make you able to pass in the full idenitifier but where would you even get that? That is like com.apple.blah.blah.Alex

**Comment by robertmeta** [comment]
For this version, I am going to add identifier matching and going to consider 2 way comms for version 3.0

**Comment by robertmeta** [comment]
Use the full long name to use voices that have dupes.
