### ISSUE TITLE
migrate to org files from md?

### ISSUE THREAD

**Issue by tvraman** [robertmeta/swiftmac#30]
For files that are intended to be checked into the emacspeak repo, I'd like to limit ourselves to org for readme files, so we dont have a mix of md and org files

**Comment by robertmeta** [comment]
Sure, I am not married to markdown in anyway. Will switch all the markdown
files over.  

I just noticed that you can actually use a README.org and it will be picked
up by Github as an overview file.

> On Apr 16, 2024, at 19:45, T. V. Raman ***@***.***> wrote:
> 
> 
> For files that are intended to be checked into the emacspeak repo, I'd like to limit ourselves to org for readme files, so we dont have a mix of md and org files
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

--
Robert Melton
***@***.***

**Comment by tvraman** [comment]
Yes, Github has  been doing that for  a while
--

**Comment by robertmeta** [comment]
Done, will work on cleaning them up more.
