### ISSUE TITLE
Audio icons get interrupted on HEAD

### ISSUE THREAD

**Issue by parhamdoustdar** [robertmeta/swiftmac#31]
Steps to reproduce:
1. Build the HEAD version, Swiftmac reports this as 2.2.0
2. Use M-< and M-> to move to the top and bottom of a buffer
3. Note that the sounds are played and are then interrupted
4. If you have Magit set up, try navigating in the Magit status buffer, and note that when two sounds are played, the first seems to be interrupted while the second fully plays

**Comment by robertmeta** [comment]
This was an active decision I made, I am willing to discuss it.  Basically, when doing stuff quickly you can get a rather nasty backlog of icons which I really hate, so I do interrupt to only have 1 icon playing at a time. 

Bug or feature?

**Comment by robertmeta** [comment]
OK, I "fixed" this -- but I am not sure if I like the result, and reserve the right to change it back at some point.
