### ISSUE TITLE
tts_sync_state not working on swiftmac start-up

### ISSUE THREAD

**Issue by parhamdoustdar** [robertmeta/swiftmac#32]
I have been debugging why setting mac-default-speech-rate doesn't seem to take effect. I noticed that Emacspeak is sending the rate on server start, but Swiftmac isn't setting it.
Steps to reproduce:
1. Set the speech rate using C-u C-e d r 0.7 <RET>
2. Restart the TTS using C-e C-s. notice that the speech rate gets reset to default, even though all Emacs variables are still as you left them
Here is what Emacspeak sends log-swiftmac:
`tts_sync_state all 1 1 0.7`
The `0.7` is the rate that Swiftmac should be at which is getting ignored.

**Comment by robertmeta** [comment]
OK, so that means that it is not ignorable. It must be implemented. 

Easy enough to put back and I will need to go update the docs. 

I wonder if it makes sense to make that not use sync state, but to directly send it. 

> On Apr 17, 2024, at 06:04, Parham Doustdar ***@***.***> wrote:
> 
> 
> I have been debugging why setting mac-default-speech-rate doesn't seem to take effect. I noticed that Emacspeak is sending the rate on server start, but Swiftmac isn't setting it.
> Steps to reproduce:
>     • Set the speech rate using C-u C-e d r 0.7
>     • Restart the TTS using C-e C-s. notice that the speech rate gets reset to default, even though all Emacs variables are still as you left them
> Here is what Emacspeak sends log-swiftmac:
> tts_sync_state all 1 1 0.7
> The 0.7 is the rate that Swiftmac should be at which is getting ignored.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

--
Robert Melton
***@***.***

**Comment by robertmeta** [comment]
I think this clears up that tts_sync_state must be instant as well.  Will put it back.

**Comment by robertmeta** [comment]
fixed./
