### ISSUE TITLE
Unable to get inline voice changes to work

### ISSUE THREAD

**Issue by bartbunting** [robertmeta/swiftmac#34]
I have been trying to use the [{voice xxx}] tag to get voice changes to work.  I have not managed to get it working as yet.  If I do use the voice command directly in the speech server it works correctly.

this works:
tts_set_voice en-US:Alex
q {this is a test}
tts_set_voice en-AU:Lee
q {this is a test}
d
This does not:
q { [{voice en-US:Alex}] this is a test [{voice en-AU:Lee}] this is a test}
d

Here is the log output from the failing test:

soundVolume 0.1
toneVolume 0.1
voiceVolume 1.0
Enter: main
Enter: instantVersion
Enter: instantStopSpeaking
Enter: instantTtsSay
ttsSay: swiftmac 2 dot 4 dot 4: debug mode
Enter: instantStopSpeaking
Enter: replaceAllPuncs
Enter: replaceSomePuncs
Enter: replaceBasePuncs
Enter: _doSpeak :: 'swiftmac 2 dot 4 dot 4 colon  debug mode'
got line q { [{voice en-US:Alex}] this is a test [{voice en-AU:Lee}] this is a test}
Enter: isolateParams
Enter: isolateCommand
Exit: isolateParams:  [{voice en-US:Alex}] this is a test [{voice en-AU:Lee}] this is a test
Enter: queueLine
got line 
Enter: isolateParams
Enter: isolateCommand
Exit: isolateParams: 
Enter: unknownLine
Unknown command: '' ''
got line d
Enter: isolateParams
Enter: isolateCommand
Exit: isolateParams: d
got queued q  [{voice en-US:Alex}] this is a test [{voice en-AU:Lee}] this is a test
Enter: replaceAllPuncs
Enter: replaceSomePuncs
Enter: replaceBasePuncs
Enter: _doSpeak :: ' [{voice en dash US colon Alex}] this is a test [{voice en dash AU colon Lee}] this is a test'

**Comment by robertmeta** [comment]
I fear this is my ignorance, how are you triggering 
the embedding of different voices from within 
Emacspeak?  

Not required to fix it by the way, I know the exact
problem and the fix, but I am working on writing the 
lisp code and trying to understand how you would tag
in different voices.  

For example, using a different voice for comments for
example. None of the mac stuff really translates to
well.

Regardless, I know the issue and will put in a fix in
2.4.5.  But I want to understand how you are triggering 
sending like en-AU:Lee, etc. 
 


> On Apr 21, 2024, at 21:01, bartbunting ***@***.***> wrote:
> 
> 
> I have been trying to use the [{voice xxx}] tag to get voice changes to work. I have not managed to get it working as yet. If I do use the voice command directly in the speech server it works correctly.
> this works:
> tts_set_voice en-US:Alex
> q {this is a test}
> tts_set_voice en-AU:Lee
> q {this is a test}
> d
> This does not:
> q { [{voice en-US:Alex}] this is a test [{voice en-AU:Lee}] this is a test}
> d
> Here is the log output from the failing test:
> soundVolume 0.1
> toneVolume 0.1
> voiceVolume 1.0
> Enter: main
> Enter: instantVersion
> Enter: instantStopSpeaking
> Enter: instantTtsSay
> ttsSay: swiftmac 2 dot 4 dot 4: debug mode
> Enter: instantStopSpeaking
> Enter: replaceAllPuncs
> Enter: replaceSomePuncs
> Enter: replaceBasePuncs
> Enter: _doSpeak :: 'swiftmac 2 dot 4 dot 4 colon debug mode'
> got line q { [{voice en-US:Alex}] this is a test [{voice en-AU:Lee}] this is a test}
> Enter: isolateParams
> Enter: isolateCommand
> Exit: isolateParams: [{voice en-US:Alex}] this is a test [{voice en-AU:Lee}] this is a test
> Enter: queueLine
> got line
> Enter: isolateParams
> Enter: isolateCommand
> Exit: isolateParams:
> Enter: unknownLine
> Unknown command: '' ''
> got line d
> Enter: isolateParams
> Enter: isolateCommand
> Exit: isolateParams: d
> got queued q [{voice en-US:Alex}] this is a test [{voice en-AU:Lee}] this is a test
> Enter: replaceAllPuncs
> Enter: replaceSomePuncs
> Enter: replaceBasePuncs
> Enter: _doSpeak :: ' [{voice en dash US colon Alex}] this is a test [{voice en dash AU colon Lee}] this is a test'
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

--
Robert Melton
***@***.***

**Comment by bartbunting** [comment]
The above was constructed by hand.
However using something like:
(swiftmac-define-voice 'karen " [{voice en-AU:karen}] ")

should likely work.

**Comment by robertmeta** [comment]
I saw that for 'paul, but how do I make it USE the Karen voice?

> On Apr 22, 2024, at 00:09, bartbunting ***@***.***> wrote:
> 
> 
> The above was constructed by hand.
> However using something like:
> (swiftmac-define-voice 'karen " [{voice en-AU:karen}] ")
> should likely work.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

--
Robert Melton
***@***.***

**Comment by bartbunting** [comment]
I don't recall exactly how it works. But basically you would use swiftmac-define-voice to redefine things like voice-Bolden and the other voices. I need to refresh my memory of how personalities are mapped to voices. Once the in-line code is working, I will figure it out. Much easier if I can actually test it.

**Comment by robertmeta** [comment]
@bartbunting inline code is back in, remember that the voice command is a code so does not go in the q but the c command.  

So with recent commit you have 

[{voice en-US:Alex}] -- and like :Alex and just en-US (same as set_lang)

Additionally, you now have pitch in this style (also a code)

[[pitch .5]]

or 

[[pitch 2.0]]
