### ISSUE TITLE
Gaps in output timing

### ISSUE THREAD

**Issue by robertmeta** [robertmeta/swiftmac#39]
This comes in two flavors, one is severe delay, suepr noticable -- this seems to be triggered by unknown things right now.  The second is a sort of slow performance when you have multiple utterances for a single line, using the build in utterance sort of queueing

**Comment by robertmeta** [comment]
@parhamdoustdar can you check if this still happens with the built depending on 5.9 of swift?  I hope we killed this one by accident.

**Comment by parhamdoustdar** [comment]
Can't reproduce this any more, seems to be fixed. Thanks!Sent from my iPhoneOn 17 Jun 2024, at 19:25, Robert Melton ***@***.***> wrote:﻿
@parhamdoustdar can you check if this still happens with the built depending on 5.9 of swift?  I hope we killed this one by accident.

**Comment by robertmeta** [comment]
sweet, closing this.  Gotta start prep-work for swift 6!
