### ISSUE TITLE
Swiftmac crashes when reading elisp code

### ISSUE THREAD

**Issue by parhamdoustdar** [robertmeta/swiftmac#41]
This has been impossible to reliably reproduce, even when I get the log and paste it into a terminal directly into Swiftmac, which makes me think that there is something about the timing of a command that causes the crash, not the order.
Here is the most reliable way I've found to reproduce the issue:
1. Open some elisp code that has an opening parenthesis in the beginning. The line also needs to be indented, so that Emacspeak would queue indent information. For example, go to line 1830 of dtk-speak.el on latest, which should be `   ((dtk-notify-process)                ; we have a live notifier`
2. Now, keep repeating the following steps until you get the main TTS stream to crash: press M-m (which should be bound to `back-to-indentation`) and then press the right arrow key so that you get to the second opening parenthesis.
Let me know if I can use anything to produce a log with more details if you can't reproduce this.

**Comment by robertmeta** [comment]
@parhamdoustdar great report, was able to reproduce. 

That said, I have no notion of what the heck might be the cause of it.

**Comment by robertmeta** [comment]
What it IS NOT: 

- Isn't audio icons, happens with them distabled 
- Isn't a simple form of race condition, happens when I put doSpeak _doSpeak on the MainActor. 

It obviously is a race / overlap of some kind.  Annoying on my machine it doesn't actually crash it just stops responding, even when I take all the do/try/catch statements outs.  So, confusing behavior. I too can't get a reproducer in the terminal, trying to double-down on that.

How can it reproduce so reliably via Emacspeak but looking at exact same data to the client by hand does not cause it?!

**Comment by parhamdoustdar** [comment]
What if you would add timestamps to the logs? That way we can see how much of a delay causes it to happen? When it doesn't happen in the terminal, makes me think the way to reproduce it is to send those commands at a certain time?Sent from my iPhoneOn 14 May 2024, at 21:35, Robert Melton ***@***.***> wrote:﻿
What it IS NOT:

Isn't audio icons, happens with them distabled
Isn't a simple form of race condition, happens when I put doSpeak _doSpeak on the MainActor.

It obviously is a race / overlap of some kind.  Annoying on my machine it doesn't actually crash it just stops responding, even when I take all the do/try/catch statements outs.  So, confusing behavior. I too can't get a reproducer in the terminal, trying to double-down on that.
How can it reproduce so reliably via Emacspeak but looking at exact same data to the client by hand does not cause it?!

**Comment by robertmeta** [comment]
Yep, a good idea.  

I thought about it, but would need a custom playback system too.

At this point, worth doing, basically, I am going to created a timed "recording" and a
"playback" system.  

> On May 15, 2024, at 01:19, Parham Doustdar ***@***.***> wrote:
> 
> 
> What if you would add timestamps to the logs? That way we can see how much of a delay causes it to happen? When it doesn't happen in the terminal, makes me think the way to reproduce it is to send those commands at a certain time?Sent from my iPhoneOn 14 May 2024, at 21:35, Robert Melton ***@***.***> wrote:﻿ 
> What it IS NOT: 
> 
> Isn't audio icons, happens with them distabled 
> Isn't a simple form of race condition, happens when I put doSpeak _doSpeak on the MainActor. 
> 
> It obviously is a race / overlap of some kind. Annoying on my machine it doesn't actually crash it just stops responding, even when I take all the do/try/catch statements outs. So, confusing behavior. I too can't get a reproducer in the terminal, trying to double-down on that. 
> How can it reproduce so reliably via Emacspeak but looking at exact same data to the client by hand does not cause it?! 
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

--
Robert Melton
***@***.***

**Comment by parhamdoustdar** [comment]
Ooh that’s awesome! Would be great to see if you can do that in the testing framework so we can turn issues like these into tests.
